# Generated by Django 4.0.4 on 2022-06-03 16:59

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cet',
            fields=[
                ('idCet', models.AutoField(db_column='idCet', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 6, 3, 18, 59, 46, 284237))),
                ('ne_procitano_Korisnik_1', models.CharField(db_column='ne_procitano_Korisnik_1', max_length=1)),
                ('ne_procitano_Korisnik_2', models.CharField(db_column='ne_procitano_Korisnik_2', max_length=1)),
            ],
            options={
                'db_table': 'cet',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('idmodel', models.AutoField(db_column='idModel', primary_key=True, serialize=False)),
                ('carreviewlink', models.CharField(blank=True, db_column='CarReviewLink', max_length=500, null=True)),
                ('brend', models.CharField(db_column='Brend', max_length=100)),
                ('naziv_modela', models.CharField(db_column='Naziv modela', max_length=100)),
                ('godisteOd', models.IntegerField(db_column='GodisteOd', default=0)),
                ('godisteDo', models.IntegerField(db_column='GodisteDo', default=0)),
            ],
            options={
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('idoglas', models.AutoField(db_column='idOglas', primary_key=True, serialize=False)),
                ('tip', models.CharField(db_column='Tip', max_length=1)),
                ('cena', models.IntegerField(blank=True, db_column='Cena', null=True)),
                ('boost', models.IntegerField(blank=True, db_column='Boost', null=True)),
                ('grad', models.CharField(db_column='Grad', max_length=45)),
                ('opis', models.TextField(db_column='Opis')),
                ('snaga', models.IntegerField(db_column='Snaga', default=0)),
                ('kilometraza', models.IntegerField(db_column='Kilometraza', default=0)),
                ('godiste', models.IntegerField(db_column='Godiste', default=0)),
                ('karoserija', models.CharField(blank=True, db_column='Karoserija', default='limuzina', max_length=20)),
                ('model_idmodel', models.ForeignKey(db_column='Model_idModel', on_delete=django.db.models.deletion.CASCADE, to='CarHub.model')),
            ],
            options={
                'db_table': 'oglas',
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('kontakt_telefon', models.CharField(db_column='Kontakt telefon', max_length=45)),
                ('slika', models.FileField(blank=True, db_column='Slika', default='imgs/default.jpg', null=True, upload_to='imgs/')),
                ('uloga', models.CharField(db_column='Uloga', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'korisnik',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Slike',
            fields=[
                ('idSlike', models.AutoField(db_column='idSlike', primary_key=True, serialize=False)),
                ('slike', models.FileField(db_column='Slike', null=True, upload_to='imgs/')),
                ('fk_oglas', models.ForeignKey(db_column='fk_Oglas', on_delete=django.db.models.deletion.CASCADE, to='CarHub.oglas')),
            ],
            options={
                'db_table': 'slike',
            },
        ),
        migrations.CreateModel(
            name='SacuvaniOglasi',
            fields=[
                ('idsacuvanioglasi', models.AutoField(db_column='idSacuvaniOglasi', primary_key=True, serialize=False)),
                ('korisnik_id', models.ForeignKey(db_column='korisnik', on_delete=django.db.models.deletion.CASCADE, related_name='korisnik_s', to=settings.AUTH_USER_MODEL)),
                ('oglas_id', models.ForeignKey(db_column='oglas_id', on_delete=django.db.models.deletion.CASCADE, related_name='oglas_id_s', to='CarHub.oglas')),
            ],
            options={
                'db_table': 'sacuvanioglasi',
            },
        ),
        migrations.CreateModel(
            name='Poruke',
            fields=[
                ('idporuke', models.AutoField(db_column='idPoruke', primary_key=True, serialize=False)),
                ('sadrzaj', models.CharField(blank=True, db_column='Poruka', max_length=500, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 6, 3, 18, 59, 46, 285236))),
                ('cet_idcet', models.ForeignKey(db_column='Cet_idCet', on_delete=django.db.models.deletion.CASCADE, to='CarHub.cet')),
                ('idKorisnikaPoslao', models.ForeignKey(db_column='Korisnik_idKorisnika', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poruke',
            },
        ),
        migrations.AddField(
            model_name='oglas',
            name='vlasnik_id',
            field=models.ForeignKey(db_column='vlasnik_auta', on_delete=django.db.models.deletion.CASCADE, related_name='vlasnik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(db_column='ocena')),
                ('korisnik', models.ForeignKey(db_column='korisnik', on_delete=django.db.models.deletion.CASCADE, related_name='korisnik', to=settings.AUTH_USER_MODEL)),
                ('ocenio', models.ForeignKey(db_column='ocenio', on_delete=django.db.models.deletion.CASCADE, related_name='ocenio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocena',
            },
        ),
        migrations.CreateModel(
            name='MojiOglasi',
            fields=[
                ('idmojioglasi', models.AutoField(db_column='idMojiOglasi', primary_key=True, serialize=False)),
                ('korisnik_id', models.ForeignKey(db_column='korisnik', on_delete=django.db.models.deletion.CASCADE, related_name='korisnik_m', to=settings.AUTH_USER_MODEL)),
                ('oglas_id', models.ForeignKey(db_column='oglas_id', on_delete=django.db.models.deletion.CASCADE, related_name='oglas_id_m', to='CarHub.oglas')),
            ],
            options={
                'db_table': 'mojioglasi',
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('idkomentar', models.AutoField(db_column='idKomentar', primary_key=True, serialize=False)),
                ('sadrzaj', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 6, 3, 18, 59, 46, 284237))),
                ('autor', models.ForeignKey(db_column='autor', on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
                ('profilKorisnika', models.ForeignKey(db_column='profilKorisnika', on_delete=django.db.models.deletion.CASCADE, related_name='profilKorisnika', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'komentar',
            },
        ),
        migrations.CreateModel(
            name='Datumi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumOd', models.DateField()),
                ('datumDo', models.DateField()),
                ('fk_oglas', models.ForeignKey(db_column='fk_Oglas', on_delete=django.db.models.deletion.CASCADE, to='CarHub.oglas')),
            ],
        ),
        migrations.AddField(
            model_name='cet',
            name='idkorisnika1',
            field=models.ForeignKey(db_column='idKorisnika1', on_delete=django.db.models.deletion.CASCADE, related_name='idkorisnika1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cet',
            name='idkorisnika2',
            field=models.ForeignKey(db_column='idKorisnika2', on_delete=django.db.models.deletion.CASCADE, related_name='idkorisnika2', to=settings.AUTH_USER_MODEL),
        ),
    ]
