# Generated by Django 4.0.4 on 2022-06-02 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cet',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 16, 9, 59, 929752)),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 16, 9, 59, 930749)),
        ),
        migrations.AlterField(
            model_name='poruke',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 16, 9, 59, 931747)),
        ),
    ]
