# Generated by Django 4.0.4 on 2022-05-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('idmodel', models.AutoField(db_column='idModel', primary_key=True, serialize=False)),
                ('carreviewlink', models.CharField(blank=True, db_column='CarReviewLink', max_length=500, null=True)),
                ('brend', models.CharField(db_column='Brend', max_length=100)),
                ('naziv_modela', models.CharField(db_column='Naziv modela', max_length=100)),
                ('godiste', models.IntegerField(db_column='Godiste')),
            ],
            options={
                'db_table': 'model',
            },
        ),
    ]
