# Generated by Django 4.0.4 on 2022-06-03 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cet',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 19, 0, 12, 921986)),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 19, 0, 12, 922980)),
        ),
        migrations.AlterField(
            model_name='poruke',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 19, 0, 12, 923978)),
        ),
    ]
