# Generated by Django 4.0.4 on 2022-05-23 01:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarHub', '0002_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('idoglas', models.AutoField(db_column='idOglas', primary_key=True, serialize=False)),
                ('tip', models.CharField(db_column='Tip', max_length=1)),
                ('cena', models.IntegerField(blank=True, db_column='Cena', null=True)),
                ('boost', models.IntegerField(blank=True, db_column='Boost', null=True)),
                ('grad', models.CharField(db_column='Grad', max_length=45)),
                ('slike', models.FileField(db_column='Slike', null=True, upload_to='imgs/')),
                ('model_idmodel', models.ForeignKey(db_column='Model_idModel', on_delete=django.db.models.deletion.DO_NOTHING, to='CarHub.model')),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('idkomentar', models.AutoField(db_column='idKomentar', primary_key=True, serialize=False)),
                ('sadrzaj', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 5, 23, 3, 14, 17, 20442))),
                ('autor', models.ForeignKey(db_column='autor', on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
                ('profilKorisnika', models.ForeignKey(db_column='profilKorisnika', on_delete=django.db.models.deletion.CASCADE, related_name='profilKorisnika', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'komentar',
            },
        ),
    ]
