# Generated by Django 4.0.4 on 2022-05-20 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarHub', '0003_model_karoserija_model_kilometraza_model_snaga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='model_idmodel',
            field=models.ForeignKey(db_column='Model_idModel', on_delete=django.db.models.deletion.CASCADE, to='CarHub.model'),
        ),
        migrations.AlterModelTable(
            name='oglas',
            table='oglas',
        ),
    ]
