# Generated by Django 4.0.4 on 2022-05-23 23:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarHub', '0003_oglas_komentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 1, 31, 21, 119806)),
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(db_column='ocena')),
                ('korisnik', models.ForeignKey(db_column='korisnik', on_delete=django.db.models.deletion.CASCADE, related_name='korisnik', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocena',
            },
        ),
    ]
