# Generated by Django 4.0.4 on 2022-05-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarHub', '0003_oglas')
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='karoserija',
            field=models.CharField(blank=True, db_column='Karoserija', default='limuzina', max_length=20),
        ),
        migrations.AddField(
            model_name='model',
            name='kilometraza',
            field=models.IntegerField(db_column='Kilometraza', default=0),
        ),
        migrations.AddField(
            model_name='model',
            name='snaga',
            field=models.IntegerField(db_column='Snaga', default=0),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='slika',
            field=models.CharField(blank=True, db_column='Slika', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('idoglas', models.AutoField(db_column='idOglas', primary_key=True, serialize=False)),
                ('tip', models.CharField(db_column='Tip', max_length=1)),
                ('cena', models.IntegerField(blank=True, db_column='Cena', null=True)),
                ('boost', models.IntegerField(blank=True, db_column='Boost', null=True)),
                ('grad', models.CharField(db_column='Grad', max_length=45)),
                ('slike', models.FileField(db_column='Slike', null=True, upload_to='imgs/')),
                ('model_idmodel', models.ForeignKey(db_column='Model_idModel', on_delete=django.db.models.deletion.DO_NOTHING, to='CarHub.model')),
            ],
        ),
    ]
