# Generated by Django 4.0.4 on 2022-05-26 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarHub', '0004_alter_komentar_timestamp_ocena'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocena',
            name='ocenio',
            field=models.ForeignKey(db_column='ocenio', default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ocenio', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='komentar',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 16, 26, 28, 432592)),
        ),
    ]
