# Generated by Django 4.0.4 on 2022-05-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarHub', '0006_remove_model_godiste_model_godistedo_model_godisteod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='slika',
            field=models.ImageField(db_column='Slika', null=True, upload_to='imgs/'),
        ),
    ]
