# Generated by Django 4.0.4 on 2022-05-21 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarHub', '0007_remove_model_godiste_model_godistedo_model_godisteod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oglas',
            name='slike',
        ),
        migrations.CreateModel(
            name='Slike',
            fields=[
                ('idSlike', models.AutoField(db_column='idSlike', primary_key=True, serialize=False)),
                ('slike', models.FileField(db_column='Slike', null=True, upload_to='imgs/')),
                ('fk_oglas', models.ForeignKey(db_column='fk_Oglas', on_delete=django.db.models.deletion.CASCADE, to='CarHub.oglas')),
            ],
            options={
                'db_table': 'slike',
            },
        ),
    ]
