-- MySQL Script generated by MySQL Workbench
-- Thu Apr 21 21:56:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 4HP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 4HP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `4HP` DEFAULT CHARACTER SET utf8 ;
USE `4HP` ;

-- -----------------------------------------------------
-- Table `4HP`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4HP`.`Korisnik` (
  `idKorisnika` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `Korisnicko ime` VARCHAR(45) NOT NULL,
  `Lozinka` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Kontakt telefon` VARCHAR(45) NOT NULL,
  `Slika` VARCHAR(100) NULL,
  `Uloga` CHAR(1) NOT NULL,
  PRIMARY KEY (`idKorisnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4HP`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4HP`.`Model` (
  `idModel` INT NOT NULL AUTO_INCREMENT,
  `CarReviewLink` VARCHAR(500) NULL,
  `Brend` VARCHAR(100) NOT NULL,
  `Naziv modela` VARCHAR(100) NOT NULL,
  `Godiste` INT NOT NULL,
  PRIMARY KEY (`idModel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4HP`.`Oglas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4HP`.`Oglas` (
  `idOglas` INT NOT NULL AUTO_INCREMENT,
  `Tip` CHAR(1) NOT NULL,
  `Cena` INT NULL,
  `Boost` TINYINT NULL,
  `Grad` VARCHAR(45) NOT NULL,
  `Model_idModel` INT NOT NULL,
  PRIMARY KEY (`idOglas`),
  INDEX `fk_Oglas_Model1_idx` (`Model_idModel` ASC) VISIBLE,
  CONSTRAINT `fk_Oglas_Model1`
    FOREIGN KEY (`Model_idModel`)
    REFERENCES `4HP`.`Model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4HP`.`Termin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4HP`.`Termin` (
  `idTermin` INT NOT NULL AUTO_INCREMENT,
  `DatumOd` DATETIME NOT NULL,
  `DatumDo` DATETIME NOT NULL,
  `Korisnik_idKorisnika` INT NOT NULL,
  `Oglas_idOglas` INT NOT NULL,
  PRIMARY KEY (`idTermin`),
  INDEX `fk_Termin_Korisnik1_idx` (`Korisnik_idKorisnika` ASC) VISIBLE,
  INDEX `fk_Termin_Oglas1_idx` (`Oglas_idOglas` ASC) VISIBLE,
  CONSTRAINT `fk_Termin_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnika`)
    REFERENCES `4HP`.`Korisnik` (`idKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Termin_Oglas1`
    FOREIGN KEY (`Oglas_idOglas`)
    REFERENCES `4HP`.`Oglas` (`idOglas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4HP`.`Komentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4HP`.`Komentar` (
  `idKomentar` INT NOT NULL AUTO_INCREMENT,
  `Komentar` VARCHAR(500) NULL,
  `Korisnik_idKorisnika_Postavio` INT NOT NULL,
  `Korisnik_idKorisnika1_NaProfilu` INT NOT NULL,
  PRIMARY KEY (`idKomentar`),
  INDEX `fk_Komentar_Korisnik1_idx` (`Korisnik_idKorisnika_Postavio` ASC) VISIBLE,
  INDEX `fk_Komentar_Korisnik2_idx` (`Korisnik_idKorisnika1_NaProfilu` ASC) VISIBLE,
  CONSTRAINT `fk_Komentar_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnika_Postavio`)
    REFERENCES `4HP`.`Korisnik` (`idKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Komentar_Korisnik2`
    FOREIGN KEY (`Korisnik_idKorisnika1_NaProfilu`)
    REFERENCES `4HP`.`Korisnik` (`idKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4HP`.`Cet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4HP`.`Cet` (
  `idCet` INT NOT NULL,
  `Korisnik_idKorisnika` INT NOT NULL,
  `Korisnik_idKorisnika1` INT NOT NULL,
  `ip` VARCHAR(30) NULL,
  PRIMARY KEY (`idCet`),
  INDEX `fk_Cet_Korisnik_idx` (`Korisnik_idKorisnika` ASC) VISIBLE,
  INDEX `fk_Cet_Korisnik1_idx` (`Korisnik_idKorisnika1` ASC) VISIBLE,
  CONSTRAINT `fk_Cet_Korisnik`
    FOREIGN KEY (`Korisnik_idKorisnika`)
    REFERENCES `4HP`.`Korisnik` (`idKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cet_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnika1`)
    REFERENCES `4HP`.`Korisnik` (`idKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4HP`.`Poruke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4HP`.`Poruke` (
  `idPoruke` INT NOT NULL,
  `Poruka` VARCHAR(500) NULL,
  `Cet_idCet` INT NOT NULL,
  `Korisnik_idKorisnika` INT NOT NULL,
  PRIMARY KEY (`idPoruke`),
  INDEX `fk_Poruke_Cet1_idx` (`Cet_idCet` ASC) VISIBLE,
  INDEX `fk_Poruke_Korisnik1_idx` (`Korisnik_idKorisnika` ASC) VISIBLE,
  CONSTRAINT `fk_Poruke_Cet1`
    FOREIGN KEY (`Cet_idCet`)
    REFERENCES `4HP`.`Cet` (`idCet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Poruke_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnika`)
    REFERENCES `4HP`.`Korisnik` (`idKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4HP`.`SacuvaniOglasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4HP`.`SacuvaniOglasi` (
  `idSacuvaniOglasi` INT NOT NULL,
  `Korisnik_idKorisnika` INT NOT NULL,
  `Oglas_idOglas` INT NOT NULL,
  PRIMARY KEY (`idSacuvaniOglasi`, `Korisnik_idKorisnika`),
  INDEX `fk_SacuvaniOglasi_Korisnik1_idx` (`Korisnik_idKorisnika` ASC) VISIBLE,
  INDEX `fk_SacuvaniOglasi_Oglas1_idx` (`Oglas_idOglas` ASC) VISIBLE,
  CONSTRAINT `fk_SacuvaniOglasi_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnika`)
    REFERENCES `4HP`.`Korisnik` (`idKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SacuvaniOglasi_Oglas1`
    FOREIGN KEY (`Oglas_idOglas`)
    REFERENCES `4HP`.`Oglas` (`idOglas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4HP`.`MojiOglasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4HP`.`MojiOglasi` (
  `idMojiOglasi` INT NOT NULL,
  `Korisnik_idKorisnika` INT NOT NULL,
  `Oglas_idOglas` INT NOT NULL,
  PRIMARY KEY (`idMojiOglasi`, `Korisnik_idKorisnika`),
  INDEX `fk_MojiOglasi_Korisnik1_idx` (`Korisnik_idKorisnika` ASC) VISIBLE,
  INDEX `fk_MojiOglasi_Oglas1_idx` (`Oglas_idOglas` ASC) VISIBLE,
  CONSTRAINT `fk_MojiOglasi_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnika`)
    REFERENCES `4HP`.`Korisnik` (`idKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MojiOglasi_Oglas1`
    FOREIGN KEY (`Oglas_idOglas`)
    REFERENCES `4HP`.`Oglas` (`idOglas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4HP`.`Ocena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4HP`.`Ocena` (
  `idOcena` INT NOT NULL,
  `Ocena` INT NULL,
  `Korisnik_idKorisnika_Postavio` INT NOT NULL,
  `Korisnik_idKorisnika1_NaProfilu` INT NOT NULL,
  PRIMARY KEY (`idOcena`),
  INDEX `fk_Ocena_Korisnik1_idx` (`Korisnik_idKorisnika_Postavio` ASC) VISIBLE,
  INDEX `fk_Ocena_Korisnik2_idx` (`Korisnik_idKorisnika1_NaProfilu` ASC) VISIBLE,
  CONSTRAINT `fk_Ocena_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnika_Postavio`)
    REFERENCES `4HP`.`Korisnik` (`idKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocena_Korisnik2`
    FOREIGN KEY (`Korisnik_idKorisnika1_NaProfilu`)
    REFERENCES `4HP`.`Korisnik` (`idKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'user1' IDENTIFIED BY 'airmax99';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
